name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: test-frontend
      run: |
        cd frontend
        yarn install
        yarn test
    - name: test-client
      run: |
        cd client
        sudo apt-get install python3-setuptools
        pip3 install -r requirements.txt
        python3 src/_unit_tests.py
    - name: systest-client
      run: |
        cd client
        sh sys_test.sh
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the frontend.
      run: |
        cd frontend
        yarn install
        yarn build:prod
    - name: Package the client
      run: |
        cd client
        pip3 install -r requirements.txt
        pip3 install pyinstaller
        pyinstaller src/main.py --onefile --hidden-import csv
        sh build_windows_exe.sh
    - name: Archive the production artifact.
      uses: actions/upload-artifact@v1
      with:
        name: telemetry-forwarding-client-windows
        path: dist
